[package]
name = "esig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.27.2"
egui_plot = "0.27.2"
emath = "0.27.2"
rayon = "1.10.0"
rfd = "0.14.1"
rustfft = "6.2.0"
