name: Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Bundle
        run: sudo apt-get install -y makeself && ./scripts/bundle.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: esig-linux-x86_64
          path: target/release/ESig.run

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Rename
        run: mv target/release/esig.exe target/release/ESig.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: esig-windows-x86_64
          path: target/release/ESig.exe

  build-macos:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Bundle
        run: ./scripts/bundle.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: esig-macos-x86_64
          path: target/release/ESig.dmg
